name: 'Upload Supabase Docs'
description: 'Upload project documentation to Supabase storage and database'
author: 'Rafał Berezin'
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for accessing repository data.'
    required: true
  supabase-url:
    description: 'Supabase project URL.'
    required: true
  supabase-key:
    description:
      'Supabase project API key with select, insert, update and delete
      permissions in the specified storage bucket.'
    required: true
  articles-path:
    description: 'Path to documentation articles directory.'
    required: true
    default: 'docs/articles'
  assets-path:
    description: 'Path to documentation assets directory.'
    required: false
  meta-path:
    description: 'Path to metadata file. (.yml, .yaml or .json)'
    required: false
  storage-bucket:
    description: 'Supabase storage bucket that stores documentation files.'
    required: true
  storage-articles-dir:
    description: 'Path to directory that stores articles in the storage bucket.'
    required: true
    default: 'articles'
  storage-assets-dir:
    description:
      "Path to directory that stores assets in the storage bucket. Required when
      'assets-path' is specified."
    required: false
  trim-prefixes:
    description:
      'Whether to trim numeric prefixes like 01- from uploaded article file and
      directory names. (boolean)'
    required: true
    default: 'true'
  meta-table:
    description: 'Database table that stores project metadata.'
    required: false
  column-mappings:
    description:
      'A string representation of yaml object that mapps generated column names
      to custom ones. Map to _ to omit column.'

runs:
  using: 'node20'
  main: 'dist/index.js'
