name: Feature Request
description: |
  Suggest a new feature or improvement for Supabase Upload Docs Action
title: '[FEATURE]: '
labels:
  - enhancement

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!
        Before submitting, check the [v2 Roadmap](https://rafalberezin.dev/projects/supabase-upload-docs-action/v2-roadmap).
        Some changes may already be planned.

  - type: checkboxes
    id: checks
    attributes:
      label: Please confirm the following before submitting
      options:
        - label: |
            This feature aligns with the [project scope](https://rafalberezin.dev/projects/supabase-upload-docs-action/contributing#project-scope)
          required: true
        - label: This feature has not already been requested
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: |
        A clear and concise description of what problem this feature would solve.
      placeholder: Right now, I can't...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: |
        A clear and concise description of the solution you want to be implemented.
      placeholder: I would like the action to...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Use Case
      description: |
        Provide an example of how you would use this feature in your documentation workflow.
      placeholder: |
        Using this new feature i can...

        With this example configuration:

        ```yaml
        - uses: rafalberezin@supabase-upload-docs-action@v1
          with:
            new-feature: value
            # Other inputs...
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: |
        A clear and concise description of any alternative solutions you've considered.
      placeholder: |
        Describe any workarounds or alternative approaches you've considered.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      multiple: false
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        Add any other context, screenshots, or mock-ups about the feature request here.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description:
        By submitting this issue, you agree to follow our [Code of
        Conduct](https://github.com/rafalberezin/supabase-upload-docs-action/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
